use_frameworks!

target 'AutoCompleteAccessoryView_Example' do
  pod 'AutoCompleteAccessoryView', :path => '../'

  pod 'EasyClosure'

  target 'AutoCompleteAccessoryView_Tests' do
    inherit! :search_paths


  end
end
