use_frameworks!

source = 'https://github.com/MatthewMerritt/EasyClosure.git'

target 'AutoCompleteAccessoryView_Example' do
  pod 'AutoCompleteAccessoryView', :path => '../'

  pod 'EasyClosure', :git => 'https://github.com/MatthewMerritt/EasyClosure.git'

  
  target 'AutoCompleteAccessoryView_Tests' do
    inherit! :search_paths


  end
end
