language: objective-c
osx_image: xcode11.3

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=SwiftDate.xcodeproj
  - IOS_FRAMEWORK_SCHEME="AutoCompleteAccessoryView"
  matrix:
    - DESTINATION="OS=13.0,name=iPhone X"          SCHEME="$IOS_FRAMEWORK_SCHEME"

script:
  # Ensures that the return code from xcodebuild is passed along to xcpretty
  - set -o pipefail
  
  # Runs the tests in Debug and Release configurations | xcpretty
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty
#  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty

# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

#osx_image: xcode11.3
#language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
#script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/AutoCompleteAccessoryView.xcworkspace -scheme AutoCompleteAccessoryView-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
