language: objective-c
osx_image: xcode11.2
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
    #- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/AutoCompleteAccessoryView.xcworkspace -scheme AutoCompleteAccessoryView-Example -sdk iphonesimulator12.2 ONLY_ACTIVE_ARCH=NO | xcpretty

    - set -o pipefail && xcodebuild test -workspace Example/AutoCompleteAccessoryView.xcworkspace -scheme AutoCompleteAccessoryView-Example -destination 'platform=iOS Simulator,name=iPhone 11 Pro' -configuration Debug | xcpretty -c

    - pod lib lint
