language: objective-c
osx_image: xcode11
name: "iPhone X (iOS 13.0)"

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
    # - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/AutoCompleteAccessoryView.xcworkspace -scheme AutoCompleteAccessoryView-Example -sdk iphonesimulator12.2 ONLY_ACTIVE_ARCH=NO | xcpretty

- set -o pipefail && xcodebuild clean test -enableCodeCoverage YES -workspace Example/AutoCompleteAccessoryView.xcworkspace -scheme AutoCompleteAccessoryView-Example -destination 'platform=iOS Simulator,OS=13.0,name=iPhone 11' | xcpretty

- pod lib lint
